### ISSUE TITLE
python版本在ubuntu下测试失败

### ISSUE THREAD

**Issue by qingyuan0o0** [hksanduo/cloudflare-api-v4-and-v6-ddns#1]
报错的地方是
Traceback (most recent call last):
  File "/usr/local/bin/cf-ddns.py", line 200, in <module>
    main(argc,argv)
  File "/usr/local/bin/cf-ddns.py", line 193, in main
    updateRecordAndZone()
  File "/usr/local/bin/cf-ddns.py", line 136, in updateRecordAndZone
    CFRECORD_V6_ID = getCFRecordId(CFZONE_ID,CFRECORD_NAME,'v6')
  File "/usr/local/bin/cf-ddns.py", line 109, in getCFRecordId
    CFRECORD_V6_ID = re.json()['result'][1]['id']

**Comment by qingyuan0o0** [comment]
经过2个台ubuntu的测试发现，config.ini中的cfrecord_v6_id =没办法自动填写到配置中，现在我的ipv4地址是没办法自动获取的大型局域网地址，所以我把配置中的wan_ipv4 = false,但是在运行py后发现自动给改成true了没办法只更新ipv6吗？

**Comment by hksanduo** [comment]
Hi,很高兴你能使用我写的项目并提出问题，你遇到的问题我已经定位到了，是判断的逻辑出了问题，我及时修改，稍后您可以再尝试一下

**Comment by hksanduo** [comment]
> 
我感觉您这边通过http://ipv6.icanhazip.com无法获取ipv6地址，您能执行命令：curl http://ipv6.icanhazip.com，看一下是否能获取到ipv6地址

**Comment by hksanduo** [comment]
> 经过2个台ubuntu的测试发现，config.ini中的cfrecord_v6_id =没办法自动填写到配置中，现在我的ipv4地址是没办法自动获取的大型局域网地址，所以我把配置中的wan_ipv4 = false,但是在运行py后发现自动给改成true了没办法只更新ipv6吗？

我感觉您这边通过[http://ipv6.icanhazip.com无法获取ipv6地址，您能执行命令：curl](http://ipv6.icanhazip.xn--comipv6%2C:curl-pm3uj98crocu3riia374npkhe3sr89ae50hmxng60a/) [http://ipv6.icanhazip.com，看一下是否能获取到ipv6地址](http://ipv6.icanhazip.xn--com%2Cipv6-309lrd734cx2ey3an52a4g587tj55crovb62k/)

**Comment by qingyuan0o0** [comment]
测试执行curl http://ipv6.icanhazip.com
可以正常返回2409:8a34:。。。。

**Comment by hksanduo** [comment]
> 测试执行curl http://ipv6.icanhazip.com 可以正常返回2409:8a34:。。。。

您这边能执行测试一下：curl http://ipv4.icanhazip.com/

**Comment by qingyuan0o0** [comment]
嗯，这个可以正常返回，不过是公网出口的地址，端口不可达这台ubuntu，所以ipv4是无用的。。如果都更新上去，这个ipv6域名就没办法使用了。。

**Comment by qingyuan0o0** [comment]
经过测试，我原先手动设置的AAAA记录域名，执行py脚本后会被覆盖为A记录域名

**Comment by qingyuan0o0** [comment]
输出了print(re.json)的执行结果
0 
 []
http://ipv4.icanhazip.com
get wan ipv4 address success!!!
wan ipv4 is:183.250.*.*
get wan ipv6 address success!!!
wan ipv6 is:2409:8a34:*********
WAN IP Unchanged, to update anyway use flag -f true

**Comment by hksanduo** [comment]
> 输出了print(re.json)的执行结果 0 [] http://ipv4.icanhazip.com get wan ipv4 address success!!! wan ipv4 is:183.250._._ get wan ipv6 address success!!! wan ipv6 is:2409:8a34:********* WAN IP Unchanged, to update anyway use flag -f true

您好，之前代码设计，其中wan_is_ipv4和wan_is_ipv6两个参数主要是方便判断是否进行更新DNS信息，并且这两个参数是程序自动配置的，您遇到的这个问题，是我设计的缺陷，我刚才已经修改了并重新提交，现在您可以尝试一下

**Comment by qingyuan0o0** [comment]
好的，感谢作者^_^，测试后可以只更新ipv6了

**Comment by hksanduo** [comment]
> 好的，感谢作者^_^，测试后可以只更新ipv6了

客气了，如果没问题，我就将该issues关闭了，有问题及时提issues
